### ISSUE TITLE
Issues with Watch-only wallet ONLY

### ISSUE THREAD

**Issue by odiferousmint** [oasin/php-electrum-api#1]
Hey. I submitted the issue here: https://github.com/spesmilo/electrum/issues/7841

I am not sure if this is an issue with Electrum itself, which it might be considering that I tried it with both this and https://github.com/matasarei/JsonRPC.git and it resulted in the same error.

Note that

```
$ electrum getbalance -w ~/.electrum/wallets/watch
```

does work, so perhaps specifying the wallet path for each execution might work, although then why isn't this working?

```php
<?php

require 'vendor/autoload.php';

$client = new \Electrum\Client('http://127.0.0.1', 7777, 0, 'foo', 'foobar');

$load_wallet = new \Electrum\Request\Method\Wallet\LoadWallet($client);
$load_wallet->execute(['wallet_path' => '~/.electrum/wallets/watch']);

$balance = new \Electrum\Request\Method\Wallet\GetBalance($client);
$balance->execute();

?>
```

From this code I get `wallet not loaded`, similarly to what I get from the daemon itself:

```
E | daemon.CommandsServer | internal error while executing RPC
Traceback (most recent call last):
  File "/home/odiferousmint/.local/lib/python3.10/site-packages/electrum/daemon.py", line 237, in handle
    response['result'] = await f(*params)
  File "/home/odiferousmint/.local/lib/python3.10/site-packages/electrum/commands.py", line 142, in func_wrapper
    raise Exception('wallet not loaded')
Exception: wallet not loaded
```

It works if there is a wallet that is not watch-only. Not sure if it has to be any wallet, or the wallet holding the private key to the watch-only wallet, but regardless, I need it to work with watch-only wallets ONLY.

**Comment by odiferousmint** [comment]
It is solved. The issue was using `wallet_path` instead of `wallet` for `getbalance`. You have to use `$balance->execute(['wallet' => '~/.electrum/wallets/watch']);`.
